blank_issues_enabled: false
contact_links:
  - name: Contribution Guidelines
    url: https://github.com/Anwishta/ShopSphere/blob/main/Contribution.md
    about: Please read the contribution guidelines before creating an issue.
